version: 2
jobs:
  full-u18.04-bionic:
    docker:
      - image: mrpt/mrpt-build-env:full-bionic
    steps:
      - run:
          name: "Install dependencies"
          command: |
            apt-get update
            apt-get install software-properties-common -y
            add-apt-repository ppa:joseluisblancoc/mrpt -y
            add-apt-repository ppa:borglab/gtsam-develop -y
            apt-get install libmrpt-dev -y
            apt-get install libgtsam-no-tbb-unstable-dev libgtsam-no-tbb-dev -y
      - checkout
      - run:
          name: "Pull Submodules"
          command: |
            git submodule update --init --recursive
      - run:
          name: Generate cmake files
          command: |
            cmake -H. -Bbuild
      - run: make -C build
      - run: make CTEST_OUTPUT_ON_FAILURE=1 test -C build
#      - run: make gcov -C build
#      - run: make -C build
#      - run: bash <(curl -s https://codecov.io/bash) -X gcov -y .codecov.yml -s build
  full-u20.04-focal:
    docker:
      - image: mrpt/mrpt-build-env:full-focal
    steps:
      - run:
          name: "Install dependencies"
          command: |
            apt-get update
            apt-get install software-properties-common -y
            add-apt-repository ppa:joseluisblancoc/mrpt -y
            add-apt-repository ppa:joseluisblancoc/gtsam-develop -y
            apt-get install libmrpt-dev -y
            apt-get install libgtsam-dev libboost-all-dev -y
      - checkout
      - run:
          name: "Pull Submodules"
          command: |
            git submodule update --init --recursive
      - run:
          name: Generate cmake files
          command: |
            cmake -H. -Bbuild
      - run: make -C build
      - run: make CTEST_OUTPUT_ON_FAILURE=1 test -C build
#      - run: make gcov -C build
#      - run: make -C build
#      - run: bash <(curl -s https://codecov.io/bash) -X gcov -y .codecov.yml -s build
  clang-u18.04-bionic:
    docker:
      - image: mrpt/mrpt-build-env:full-bionic
    steps:
      - run:
          name: "Install dependencies"
          command: |
            apt-get update
            apt-get install software-properties-common -y
            add-apt-repository ppa:joseluisblancoc/mrpt -y
            add-apt-repository ppa:joseluisblancoc/gtsam-develop -y
            apt-get install libmrpt-dev -y
            apt-get install libgtsam-dev libboost-all-dev -y
      - checkout
      - run:
          name: "Pull Submodules"
          command: |
            git submodule update --init --recursive
      - run:
          name: Generate cmake files
          command: cmake -H. -Bbuild
          environment:
            CC: /usr/bin/clang-6.0
            CXX: /usr/bin/clang++-6.0
      - run: make -C build
      - run: make CTEST_OUTPUT_ON_FAILURE=1 test -C build
#      - run: make gcov -C build
#      - run: make -C build
#      - run: bash <(curl -s https://codecov.io/bash) -X gcov -y .codecov.yml -s build
workflows:
  version: 2
  build:
    jobs:
      - full-u18.04-bionic
      - full-u20.04-focal
      - clang-u18.04-bionic
